# gen config
data:
  sample_rate: 22050 # this is the wanted sample rate required for genmodel
  preprocessors: [pad_or_truncate, monolize, resample] # in that order to be applied

model:
  gen_model: 
    name: Mel
    n_fft: 512
    win_length: 512
    hop_length: 256
    n_mels: 256
    fps: 43 # sample_rate/hop_length
    output_dim: 256
  
    
  
    
    

  
  
