data:
  sample_rate: 32000 # this is the wanted sample rate required for genmodel
  preprocessors: [pad_or_truncate, monolize, resample]

model:
  gen_model: 
    name: MusicGenLarge
    version: large
    fps: 50
    output_dim: 2048
    
  
    
    

  
  
