data:
  sample_rate: 32000 # this is the wanted sample rate required for genmodel
  preprocessors: [pad_or_truncate, monolize, resample]

model:
  gen_model: 
    name: MusicGenMedium
    version: medium
    extract_layer: 17 # would be overwritten if assigned in base config
    
  
    
    

  
  
