# task config
data:
  name: key_GS
  # data_dir: '/home/lego/Database/Data'
  data_dir: '../scratch/GS/raw'
  batch_size: 8
  num_workers: 4
  max_length: 1323000  # 25s approx (30 * 44100)
  orig_sample_rate: 44100
  required_key: ['key']

model:
  peft:
    name: DiscrimProbeModule
    metric: 
      name: Accuracy
      task: multiclass
      num_labels: 24
    repr_head:
      n_classes: 24
      hidden_sizes: 512
      dropout: 0.25

training:
  accumulate_grad_batches: 8

# batch_size * accumulate_grad_batches = 64


  
  