# task config
data:
  name: key_GS
  data_dir: '/home/lego/Database/GS/key/raw'
  # data_dir: '../scratch/GS/key/raw'
  batch_size: 16
  num_workers: 0
  max_length: 1323000  # 25s approx (30 * 44100)
  orig_sample_rate: 44100
  required_key: ['key']

model:
  peft:
    name: DiscrimProbeModule
    metric: null
    repr_head:
      n_classes: 24
      hidden_sizes: 512
      dropout: 0.25
    gen_model:
      name: MusicGenSmall
      extract_layer: 0

training:
  accumulate_grad_batches: 8

# batch_size * accumulate_grad_batches = 64


  
  