# task config
data:
  name: key_GS_feature
  # data_dir: '/home/lego/Database/Data'
  data_dir: '../scratch/GS/key/'
  batch_size: 256
  num_workers: 8
  max_length: 1323000  # 25s approx (30 * 44100)
  orig_sample_rate: 44100
  required_key: ['key']

model:
  peft:
    name: DiscrimProbeModule
    metric: null
    repr_head:
      n_classes: 24
      hidden_sizes: 512
      dropout: 0.25
    use_feature: True

training:
  accumulate_grad_batches: 1

# batch_size * accumulate_grad_batches = 64


  
  