# task config
data:
  name: tempo_GS
  # data_dir: '/home/lego/Database/Data'
  data_dir: '../scratch/GS/tempo/raw'
  batch_size: 4
  num_workers: 0
  max_length: 1323000  # 30s approx (30 * 44100)
  orig_sample_rate: 44100
  required_key: ['tempo']

model:
  peft:
    name: DiscrimProbeModule
    metric: null
    repr_head:
      n_classes: 300
      hidden_sizes: 512
      dropout: 0.25

training:
  accumulate_grad_batches: 8

# batch_size * accumulate_grad_batches = 64


  
  