# task config
data:
  name: tempo_GS_feature
  # data_dir: '/home/lego/Database/Data'
  data_dir: '../Database/GS/tempo/'
  batch_size: 128
  num_workers: 0
  max_length: 1102500  # 30s approx (30 * 44100)
  orig_sample_rate: 44100
  required_key: ['tempo']

model:
  peft:
    name: DiscrimProbeModule
    metric: null
    repr_head:
      n_classes: 300
      hidden_sizes: 512
      dropout: 0.25
    use_feature: True

training:
  accumulate_grad_batches: 2

# batch_size * accumulate_grad_batches = 64


  
  