# Project base config
data:
  name: beat_tracking_on_feature
  data_dir: '/home/lego/Database/GTZAN/' # would be appended/join with child directory based on precompute model in PrecomputeModule when setting up
  batch_size: 64
  num_workers: 0
  aggregators: null #for this cache, all the time frame is aggregate into 1, no need additional aggregators
  required_key: ['beat_f'] # required target in key for meta from info

model:
  peft:
    use_feature: True
    name: SequentialProbeModule
    metric: null
    repr_head:
      n_classes: 2
      hidden_sizes: 512
      dropout: 0.25

training:
  accumulate_grad_batches: 1

# batch_size * accumulate_grad_batches = 64


  
  