# task config
data:
  name: genre_classification_MTG
  # data_dir: '/home/lego/Database/Data'
  data_dir: '../Database/MTG/raw'
  batch_size: 3
  num_workers: 2
  max_length: 1102500  # 25s approx (25 * 44100)
  orig_sample_rate: 44100
  required_key: ['label']

model:
  peft:
    name: DiscrimProbeModule
    metric: #AUROC
      task: multilabel
      num_labels: 87
    repr_head:
      n_classes: 87
      hidden_sizes: 512
      dropout: 0.25

training:
  accumulate_grad_batches: 8

# batch_size * accumulate_grad_batches = 64


  
  