# task config
data:
  name: genre_classification_MTG_fearure
  # data_dir: '/home/lego/Database/Data'
  data_dir: '../Database/MTG/' # would append with Pre-trained model name  
  batch_size: 256
  num_workers: 16
  max_length: 1102500  # 25s approx (25 * 44100)
  orig_sample_rate: 44100
  required_key: ['label']

model:
  peft:
    name: DiscrimProbeModule
    metric: #AUROC
      task: multilabel
      num_labels: 87
    repr_head:
      n_classes: 87
      hidden_sizes: 512
      dropout: 0.25
    use_feature: True

training:
  accumulate_grad_batches: 1

# batch_size * accumulate_grad_batches = 64


  
  