# Project base config
experiment:
  seed: 2024
  task: GTZAN_genre
  gen_model: musGen
  logger:
    output_dir: 'outputs/'
    type: wandb
    project: AskMuiscGen
    name: null

training:
  learning_rate: 0.0001
  weight_decay: 0.01
  epochs: 50 # max epoch
  log_step: 5
  val_check_interval: 1

  
