# Project base config
experiment:
  seed: 2024
  task: GS_tempo_feature
  gen_model: MusicGenSmall


training:
  learning_rate: 0.001
  weight_decay: 0.01
  epochs: 1000 # max epoch
  log_step: 5
  val_check_interval: 1

model:
  gen_model:
      extract_layer: 0
      agg_type: 'k-means'
      output_dim: 4096
  

  
