# Project base config
experiment:
  seed: 2024
  task: GS_key_feature
  gen_model: MusicGenMedium
  logger:
    output_dir: '../scratch/outputs/'
    # output_dir: 'cache/outputs/'
    type: wandb
    project: Giantsteps_key
    name: null

training:
  learning_rate: 0.001
  weight_decay: 0.01
  epochs: 200 # max epoch
  log_step: 5
  val_check_interval: 1

model:
  gen_model:
      extract_layer: 0
  

  
