# Project base config
experiment:
  seed: 2024
  task: MTG_genre
  gen_model: VampC
  logger:
    # output_dir: '../scratch/outputs/'
    output_dir: 'outputs/'
    type: wandb
    project: MTG_genre
    name: null

training:
  learning_rate: 0.001
  weight_decay: 0.01
  epochs: 1200 # max epoch
  log_step: 5
  val_check_interval: 1

model:
  gen_model:
      extract_layer: 15
  

  
